module.exports=[
    {typo: 'VIA,LAS TONADAS',
    replacement:'VIA LAS TONADAS'},
    {typo: 'VIA,TRIESTE',
    replacement:'VIA TRIESTE'},
    {typo: 'VIA,LAS PALMAS',
    replacement:'VIA LAS PALMAS'},
    {typo: 'VIA,TERECINA',
    replacement:'VIA TERECINA'},
    {typo: 'VIA DE LN,BANDOLA',
    replacement:'VIA DE LA BANDOLA'},
    {typo: 'VIA,ALTA',
    replacement:'VIA ALTA'},
    {typo: 'VIA,VENETO',
    replacement:'VIA VENETO'},
    {typo: 'VIA,BARBERINI',
    replacement:'VIA BARBERINI'},
    {typo: 'VIA,ENCANTADORAS',
    replacement:'VIA ENCANTADORAS'},
    {typo: 'VIA,DEL BARDO',
    replacement:'VIA DEL BARDO'},
    {typo: 'VIA,ENCINOS',
    replacement:'VIA ENCINOS'},
    {typo: 'VIA,TONGA',
    replacement:'VIA TONGA'},
    {typo: 'VIA,TAZON',
    replacement:'VIA TAZON'},
    {typo: 'VIA,CENTRE',
    replacement:'VIA CENTRE'},
    {typo: 'VIA,FELICIA',
    replacement:'VIA FELICIA'},
    {typo: 'PALM AVE,',
    replacement:'PALM AVENUE,'},
    {typo: 'CA 9',
    replacement:'CA, 9'},
    {typo: '28730 HIGHWAY,94,CAMPO,CA, 91906',
    replacement:'28730 HIGHWAY 94,CAMPO,CA, 91906'},
    {typo: 'HIGHWAY,94',
    replacement:'HIGHWAY 94'}
    
    
       
]


