module.exports=[
    {typo: 'VIA,LAS TONADAS',
    replacement:'VIA LAS TONADAS'},
    {typo: 'VIA,TRIESTE',
    replacement:'VIA TRIESTE'},
    {typo: 'VIA,LAS PALMAS',
    replacement:'VIA LAS PALMAS'},
    {typo: 'VIA,TERECINA',
    replacement:'VIA TERECINA'},
    {typo: 'VIA DE LN,BANDOLA',
    replacement:'VIA DE LA BANDOLA'},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
    {typo: '',
    replacement:' '},
       
]