module.exports=[
    {typo: 'PODIATRY APPOINTMENT=SEASIDE FOOT AND ANKLE=',
    replacement:' '},
    {typo: 'SSN',
    replacement:'SAN'},
    {typo: 'VSITA',
    replacement:'VISTA'},
    {typo: '3D',
    replacement:'3RD'},
    {typo: 'CV CA',
    replacement:'CHULA VISTA, CA'},
    {typo: 'CJAON',
    replacement:'CAJON'},
    {typo: 'FLOORSAN',
    replacement:'FLOOR SAN'},
    {typo: 'SUIT D',
    replacement:'SUITE D'},
    {typo: 'CTIY',
    replacement:'CITY'},
    {typo: 'CAMPUS PT',
    replacement:'CAMPUS POINT'},
    {typo: 'VAJJEY',
    replacement:'VALLEY'},
    {typo: 'SUIT 101',
    replacement:'SUITE 101'},
    {typo: 'MEDWAY',
    replacement:'MIDWAY'},
    {typo: '91910CHULA',
    replacement:'91910, CHULA'},
    {typo: 'YSDIRO',
    replacement:'YSIDRO'},
    {typo: '920103',
    replacement:'92103'},
    {typo: 'SUIT 4',
    replacement:'SUITE 4'},
    {typo: 'VELLEY',
    replacement:'VALLEY'},
    {typo: 'ACHULA',
    replacement:'A, CHULA'},
    {typo: '201CHULA',
    replacement:'201, CHULA'},
    {typo: '210CHULA',
    replacement:'210, CHULA'},
    {typo: '200CHULA',
    replacement:'200, CHULA'},
    {typo: '100CHULA',
    replacement:'100, CHULA'},
    {typo: '216CHULA',
    replacement:'216, CHULA'},
    {typo: '1095CHULA',
    replacement:'1095, CHULA'},
    {typo: 'STE 4 UC SAN DIEGO HEALTHSAN DIEGO', 
    replacement:', SAN DIEGO'},
    {typo: 'CAMPUES',
    replacement:'CAMPUS'},
    {typo: '532C',
    replacement:'532 C'},
    {typo: 'DIEOG',
    replacement:'DIEGO'},
    {typo: '415 RIDGEBACK',
    replacement:'1415 RIDGEBACK'},
    {typo: '1347 MADERA ST LEMON GROVE, CA 92114',
    replacement:'1347 MADERA ST, SAN DIEGO, CA, 92114'},
    {typo: 'SUITE104NATIONAL',
    replacement:'SUITE 104, NATIONAL'},
    {typo: '301NATIONAL',
    replacement:'301, NATIONAL'},
    {typo: '121SAN',
    replacement:'121, SAN'},
    {typo: '508SAN',
    replacement:'508, SAN'},
    {typo: '501LA',
    replacement:'501, LA'},
    {typo: '117ALPINE',
    replacement:'117, ALPINE'},
    {typo: 'SUITE B-107 SUITE B-107SAN DIEGO',
    replacement:'SUITE B-107, SAN DIEGO'},
    {typo: 'A-1CHULA',
    replacement:'A-1, CHULA'},
    {typo: '231 W. MAIN S.',
    replacement:'231 W MAIN ST'},
    {typo: 'SPRING RD',
    replacement:'SPRINGS RD'},
    {typo: 'SENIOR DAY CENTER CHULA VISTA',
    replacement:' '},
    {typo: 'SAN DIEGO PACE',
    replacement:' '},
    {typo: 'SOUTH BAY FOOT AND ANKLE SPECIALISTS, INC.--CHULA VISTA',
    replacement:' '},
    {typo: 'PODIATRY APPOINTMENT',
    replacement:' '},
    {typo: 'SEASIDE FOOT AND ANKLE',
    replacement:' '},
    {typo: 'DENTAL SYHC',
    replacement:' '},
    {typo: '(ALVARADO COURT MEDICAL BUILDING)',
    replacement:' '},
    {typo: 'IHS RADIOLOGY - SAN DIEGO (ALVARADO COURT MEDICAL BUILDING)',
    replacement:' '},
    {typo: 'IHS RADIOLOGY - SAN DIEGO',
    replacement:' '},
    {typo: 'SOUTHERN CALIFORNIA INTERVENTIONAL ASSOCIATES',
    replacement:' '},
    {typo: 'FRESENIUS VALLEY KIDNEY CARE MARINA BAY',
    replacement:' '},
    {typo: 'CALIFORNIA RETINA ASSOCIATES, LP/AMERICAN EYE ASSOCIATES--NATIONAL CITY',
    replacement:' '},
    {typo: 'EASTLAKE SLEEP CENTER',
    replacement:' '},
    {typo: 'SHARP CHULA VISTA',
    replacement:' '},
    {typo: 'CALIFORNIA RETINA ASSOCIATES, LP/AMERICAN EYE ASSOCIATES-- CHULA VISTA',
    replacement:' '},
    {typo: 'DIEDO',
    replacement:'DIEGO'},
    {typo: 'CV PACE',
    replacement:' '},
    {typo: '402SAN',
    replacement:'402, SAN'},
    {typo: 'SUITE 101 & 154LA MESA',
    replacement:'SUITE 101, LA MESA'},
    {typo: '1330 MADERA ST. ENCANTO, CA 92114',
    replacement:'1330 MADERA ST, SAN DIEGO, CA, 92114'},
    {typo: 'PALM AVE ',
    replacement:'PALM AVENUE '},
    {typo: 'PALM AVE,',
    replacement:'PALM AVENUE,'},
    {typo: 'SUITE 1, 3RD FLOORSAN DIEGO',
    replacement:'SUITE 1, SAN DIEGO'},
    {typo: 'SUITE 1, 3RD FLOOR SAN DIEGO',
    replacement:'SUITE 1, SAN DIEGO'},
    {typo: '3987 BATEMAN AVENUE EXT 2120 SAN DIEGO , 92154',
    replacement:'3987 BATEMAN AVENUE, EXT 2120, SAN DIEGO,CA , 92154'},
    {typo: '9444 CENTER DRIVE',
    replacement:'9444 MEDICAL CENTER DRIVE'},
    {typo: 'E 8TH NATIONAL',
    replacement:'E 8TH ST, NATIONAL'},
    {typo: 'BUILDING 3, SUITE 101 & 154 LA MESA',
    replacement:'SUITE 101, LA MESA'},
    {typo: 'BUILDING 3, SUITE 101 & 154LA MESA',
    replacement:'SUITE 101, LA MESA'},
    {typo: 'BUILDING 3',
    replacement:' '},
    {typo: 'SUITE 112EL CAJON',
    replacement:'SUITE 112, EL CAJON'},
    {typo: 'PICK UP PTP AT DTR. HOUSE 3987 BATEMAN AVENUE EXT 2120 SAN DIEGO , 92154 TO TAKE PTP BACK HOME',
    replacement:'PICK UP PTP AT DTR. HOUSE 3987 BATEMAN AVENUE, EXT 2120, SAN DIEGO,CA , 92154 TO TAKE PTP BACK HOME'},
    {typo: 'GENNESSEE',
    replacement:'GENESEE'},
    {typo: '4303 LA JOLLA VILLAGE DR.',
    replacement:'4303 VILLAGE DR,'},
    {typo: 'TRASPORTATION',
    replacement:'TRANSPORTATION'},
    {typo: '303H',
    replacement:'303 H'},
    {typo: '1141 25TH ST APT 201 SAN DIEGO 92154, CA 92154',
    replacement:'1141 25TH ST, APT 201, SAN DIEGO, CA, 92154'},
    {typo: '231 W MAIN ST. EL CAJON, CA TEL',
    replacement:'231 W MAIN ST, EL CAJON, CA, 92020 TEL'},
    {typo: 'FIFHT',
    replacement:'FIFTH'},
    {typo: 'SIUTE',
    replacement:'SUITE'},
    {typo: 'POINT.',
    replacement:'POINT'},
    {typo: '340 4TH AVE #14, CHULA VISTA, CA 91910 CHULA VISTA , CA',
    replacement:'340 4TH AVE, #14, CHULA VISTA, CA, 91910'},
    {typo: '1136 D AVE NC,',
    replacement:'1136 D AVE, NATIONAL CITY,'},
    {typo: '1845 EAST 12 STREET CHULA VISTA CA 91950',
    replacement:'1845 EAST 12 STREET NATIONAL CITY CA 91950'},
    {typo: '751 MEDICAL CENTER CT, CHULA VISTA CA 91910',
    replacement:'751 MEDICAL CENTER CT, CHULA VISTA CA 91911'},
    {typo: '9434 MEDICAL CENTER DR., 1ST FLOOR EAST 92093',
    replacement:'9434 MEDICAL CENTER DR, LA JOLLA, CA, 92093'},
    {typo: '8008 FROST ST. SAN DIEGO, CA 92193',
    replacement:'8008 FROST ST, SAN DIEGO, CA, 92123'},
    {typo: 'KEARNEY',
    replacement:'KEARNY'},
    {typo: '765 MEDICAL CENTER CT, SUITE 100, CHULA VISTA, CA, 91910',
    replacement:'765 MEDICAL CENTER CT, SUITE 100, CHULA VISTA, CA, 91911'},
    {typo: '1535 E PLAZA BLVD APT 211 NATIONAL, CA 91950',
    replacement:'1535 E PLAZA BLVD APT 211 NATIONAL CITY, CA 91950'},
    {typo: '( 1628 PALM AVENUE, SAN DIEGO, CA )',
    replacement:'1628 PALM AVENUE, SAN DIEGO, CA, 92154'},
    {typo: '3987 BATEMAN AVENUE EXT 2120 SAN DIEGO , 92154',
    replacement:'3987 BATEMAN AVENUE, EXT 2120, SAN DIEGO,CA , 92154'},
    {typo: '754 MEDICA C',
    replacement:'754 MEDICAL C'},
    {typo: 'PONIT',
    replacement:'POINT'},
    {typo: '3434 MIDWAY DRIVE SUITE 2004 SAN DIEGO92108',
    replacement:'3434 MIDWAY DRIVE SUITE 2004 SAN DIEGO CA 92110'},
    {typo: '5471 KEARNY VILLA STE',
    replacement:'5471 KEARNY VILLA ROAD STE'},
    {typo: '1388 BUCKMAN SPRINGS RD, CAMP, CA',
    replacement:'1388 BUCKMAN SPRINGS RD, CAMPO, CA'},
    {typo: '9350 CAMPUS POINT DRIVE SUITE 2A SECOND FLOOR, SAN DIEGO',
    replacement:'9350 CAMPUS POINT DRIVE SUITE 2A SECOND FLOOR, LA JOLLA'},
    {typo: 'JOYA',
    replacement:'JOLLA'},
    {typo: '463 NORTH MAGNOLIA,',
    replacement:'463 NORTH MAGNOLIA AV,'},
    {typo: '1845 12TH STREET',
    replacement:'1845 EAST 12TH STREET'},
    {typo: '637 W. WASHINGTON AVE EL CAJON, CA, EL CAJON, CA 92020',
    replacement:'637 WEST WASHINGTON AVE, EL CAJON, CA, 92020'},
    {typo: 'APT 34-104 SAN YSI, SAN YSIDRO',
    replacement:'APT 34-104, SAN YSIDRO'},
    {typo: 'UNIVERCITY',
    replacement:'UNIVERSITY'},
    {typo: '2095 WEST VISTA WAY VISTA, CA 92083',
    replacement:'1840 WEST DR, VISTA, CA, 92083'},
    {typo: '2095 WEST VISTA WAY VISTA, CA, 92083',
    replacement:'1840 WEST DR, VISTA, CA, 92083'},
    
    
    
    
    
    

    
    
    
    
    
    
    
    
    
    
    
    


    
    
    
    

    
    
    
    
    
    

    
    
    
    
    

    
    
    
    
    
    
        
]