module.exports=[
    {typo: 'PODIATRY APPOINTMENT=SEASIDE FOOT AND ANKLE=',
    replacement:' '},
    {typo: 'SSN',
    replacement:'SAN'},
    {typo: 'VSITA',
    replacement:'VISTA'},
    {typo: '3D',
    replacement:'3RD'},
    {typo: 'CV CA',
    replacement:'CHULA VISTA, CA'},
    {typo: 'CJAON',
    replacement:'CAJON'},
    {typo: 'FLOORSAN',
    replacement:'FLOOR SAN'},
    {typo: 'SUIT D',
    replacement:'SUITE D'},
    {typo: 'CTIY',
    replacement:'CITY'},
    {typo: 'CAMPUS PT',
    replacement:'CAMPUS POINT'},
    {typo: 'VAJJEY',
    replacement:'VALLEY'},
    {typo: 'SUIT 101',
    replacement:'SUITE 101'},
    {typo: 'MEDWAY',
    replacement:'MIDWAY'},
    {typo: '91910CHULA',
    replacement:'91910, CHULA'},
    {typo: 'YSDIRO',
    replacement:'YSIDRO'},
    {typo: '920103',
    replacement:'92103'},
    {typo: 'SUIT 4',
    replacement:'SUITE 4'},
    {typo: 'VELLEY',
    replacement:'VALLEY'},
    {typo: 'ACHULA',
    replacement:'A, CHULA'},
    {typo: '201CHULA',
    replacement:'201, CHULA'},
    {typo: '210CHULA',
    replacement:'210, CHULA'},
    {typo: '200CHULA',
    replacement:'200, CHULA'},
    {typo: '100CHULA',
    replacement:'100, CHULA'},
    {typo: '216CHULA',
    replacement:'216, CHULA'},
    {typo: '1095CHULA',
    replacement:'1095, CHULA'},
    {typo: 'STE 4 UC SAN DIEGO HEALTHSAN DIEGO', 
    replacement:', SAN DIEGO'},
    {typo: 'CAMPUES',
    replacement:'CAMPUS'},
    {typo: '532C',
    replacement:'532 C'},
    {typo: 'DIEOG',
    replacement:'DIEGO'},
    {typo: '415 RIDGEBACK',
    replacement:'1415 RIDGEBACK'},
    {typo: '1347 MADERA ST LEMON GROVE, CA 92114',
    replacement:'1347 MADERA ST, SAN DIEGO, CA, 92114'},
    {typo: 'SUITE104NATIONAL',
    replacement:'SUITE 104, NATIONAL'},
    {typo: '301NATIONAL',
    replacement:'301, NATIONAL'},
    {typo: '121SAN',
    replacement:'121, SAN'},
    {typo: '508SAN',
    replacement:'508, SAN'},
    {typo: '501LA',
    replacement:'501, LA'},
    {typo: '117ALPINE',
    replacement:'117, ALPINE',
    datapoint:''},
    {typo: 'SUITE B-107 SUITE B-107SAN DIEGO',
    replacement:'SUITE B-107, SAN DIEGO'},
    {typo: 'A-1CHULA',
    replacement:'A-1, CHULA'},
    {typo: '231 W. MAIN S.',
    replacement:'231 W MAIN ST'},
    {typo: 'SPRING RD',
    replacement:'SPRINGS RD'},
    {typo: 'SENIOR DAY CENTER CHULA VISTA',
    replacement:' '},
    {typo: 'SAN DIEGO PACE',
    replacement:' '},
    {typo: 'SOUTH BAY FOOT AND ANKLE SPECIALISTS, INC.--CHULA VISTA',
    replacement:' '},
    {typo: 'PODIATRY APPOINTMENT',
    replacement:' '},
    {typo: 'SEASIDE FOOT AND ANKLE',
    replacement:' '},
    {typo: 'DENTAL SYHC',
    replacement:' '},
    {typo: '(ALVARADO COURT MEDICAL BUILDING)',
    replacement:' '},
    {typo: 'IHS RADIOLOGY - SAN DIEGO (ALVARADO COURT MEDICAL BUILDING)',
    replacement:' '},
    {typo: 'IHS RADIOLOGY - SAN DIEGO',
    replacement:' '},
    {typo: 'SOUTHERN CALIFORNIA INTERVENTIONAL ASSOCIATES',
    replacement:' '},
    {typo: 'FRESENIUS VALLEY KIDNEY CARE MARINA BAY',
    replacement:' '},
    {typo: 'CALIFORNIA RETINA ASSOCIATES, LP/AMERICAN EYE ASSOCIATES--NATIONAL CITY',
    replacement:' '},
    {typo: 'EASTLAKE SLEEP CENTER',
    replacement:' '},
    {typo: 'SHARP CHULA VISTA',
    replacement:' '},
    {typo: 'CALIFORNIA RETINA ASSOCIATES, LP/AMERICAN EYE ASSOCIATES-- CHULA VISTA',
    replacement:' '},
    {typo: 'DIEDO',
    replacement:'DIEGO'},
    {typo: 'CV PACE',
    replacement:' '},
    {typo: '402SAN',
    replacement:'402, SAN'},
    {typo: 'SUITE 101 & 154LA MESA',
    replacement:'SUITE 101, LA MESA'},
    {typo: '1330 MADERA ST. ENCANTO, CA 92114',
    replacement:'1330 MADERA ST, SAN DIEGO, CA, 92114'},
    {typo: 'PALM AVE ',
    replacement:'PALM AVENUE '},
    {typo: 'PALM AVE,',
    replacement:'PALM AVENUE,'},
    {typo: 'SUITE 1, 3RD FLOORSAN DIEGO',
    replacement:'SUITE 1, SAN DIEGO'},
    {typo: 'SUITE 1, 3RD FLOOR SAN DIEGO',
    replacement:'SUITE 1, SAN DIEGO'},
    {typo: '3987 BATEMAN AVENUE EXT 2120 SAN DIEGO , 92154',
    replacement:'3987 BATEMAN AVENUE, EXT 2120, SAN DIEGO,CA , 92154'},
    {typo: '9444 CENTER DRIVE',
    replacement:'9444 MEDICAL CENTER DRIVE'},
    {typo: 'E 8TH NATIONAL',
    replacement:'E 8TH ST, NATIONAL'},
    {typo: 'BUILDING 3, SUITE 101 & 154 LA MESA',
    replacement:'SUITE 101, LA MESA'},
    {typo: 'BUILDING 3, SUITE 101 & 154LA MESA',
    replacement:'SUITE 101, LA MESA'},
    {typo: ' BUILDING ',
    replacement:' '},
    {typo: 'SUITE 112EL CAJON',
    replacement:'SUITE 112, EL CAJON'},
    {typo: 'PICK UP PTP AT DTR. HOUSE 3987 BATEMAN AVENUE EXT 2120 SAN DIEGO , 92154 TO TAKE PTP BACK HOME',
    replacement:'PICK UP PTP AT DTR. HOUSE 3987 BATEMAN AVENUE, EXT 2120, SAN DIEGO,CA , 92154 TO TAKE PTP BACK HOME'},
    {typo: 'GENNESSEE',
    replacement:'GENESEE'},
    {typo: '4303 LA JOLLA VILLAGE DR.',
    replacement:'4303 VILLAGE DR,'},
    {typo: 'TRASPORTATION',
    replacement:'TRANSPORTATION'},
    {typo: '303H',
    replacement:'303 H'},
    {typo: '1141 25TH ST APT 201 SAN DIEGO 92154, CA 92154',
    replacement:'1141 25TH ST, APT 201, SAN DIEGO, CA, 92154'},
    {typo: '231 W MAIN ST. EL CAJON, CA TEL',
    replacement:'231 W MAIN ST, EL CAJON, CA, 92020 TEL'},
    {typo: 'FIFHT',
    replacement:'FIFTH'},
    {typo: 'SIUTE',
    replacement:'SUITE'},
    {typo: 'POINT.',
    replacement:'POINT'},
    {typo: '340 4TH AVE #14, CHULA VISTA, CA 91910 CHULA VISTA , CA',
    replacement:'340 4TH AVE, #14, CHULA VISTA, CA, 91910'},
    {typo: '1136 D AVE NC,',
    replacement:'1136 D AVE, NATIONAL CITY,'},
    {typo: '1845 EAST 12 STREET CHULA VISTA CA 91950',
    replacement:'1845 EAST 12 STREET NATIONAL CITY CA 91950'},
    {typo: '751 MEDICAL CENTER CT, CHULA VISTA CA 91910',
    replacement:'751 MEDICAL CENTER CT, CHULA VISTA CA 91911'},
    {typo: '9434 MEDICAL CENTER DR., 1ST FLOOR EAST 92093',
    replacement:'9434 MEDICAL CENTER DR, LA JOLLA, CA, 92093'},
    {typo: '8008 FROST ST. SAN DIEGO, CA 92193',
    replacement:'8008 FROST ST, SAN DIEGO, CA, 92123'},
    {typo: 'KEARNEY',
    replacement:'KEARNY'},
    {typo: '765 MEDICAL CENTER CT, SUITE 100, CHULA VISTA, CA, 91910',
    replacement:'765 MEDICAL CENTER CT, SUITE 100, CHULA VISTA, CA, 91911'},
    {typo: '1535 E PLAZA BLVD APT 211 NATIONAL, CA 91950',
    replacement:'1535 E PLAZA BLVD APT 211 NATIONAL CITY, CA 91950'},
    {typo: '( 1628 PALM AVENUE, SAN DIEGO, CA )',
    replacement:'1628 PALM AVENUE, SAN DIEGO, CA, 92154'},
    {typo: '3987 BATEMAN AVENUE EXT 2120 SAN DIEGO , 92154',
    replacement:'3987 BATEMAN AVENUE, EXT 2120, SAN DIEGO,CA , 92154'},
    {typo: '754 MEDICA C',
    replacement:'754 MEDICAL C'},
    {typo: 'PONIT',
    replacement:'POINT'},
    {typo: '3434 MIDWAY DRIVE SUITE 2004 SAN DIEGO92108',
    replacement:'3434 MIDWAY DRIVE SUITE 2004 SAN DIEGO CA 92110'},
    {typo: '5471 KEARNY VILLA STE',
    replacement:'5471 KEARNY VILLA ROAD STE'},
    {typo: '1388 BUCKMAN SPRINGS RD, CAMP, CA',
    replacement:'1388 BUCKMAN SPRINGS RD, CAMPO, CA'},
    {typo: '9350 CAMPUS POINT DRIVE SUITE 2A SECOND FLOOR, SAN DIEGO',
    replacement:'9350 CAMPUS POINT DRIVE SUITE 2A SECOND FLOOR, LA JOLLA'},
    {typo: 'JOYA',
    replacement:'JOLLA'},
    {typo: '463 NORTH MAGNOLIA,',
    replacement:'463 NORTH MAGNOLIA AV,'},
    {typo: '1845 12TH STREET',
    replacement:'1845 EAST 12TH STREET'},
    {typo: '637 W. WASHINGTON AVE EL CAJON, CA, EL CAJON, CA 92020',
    replacement:'637 WEST WASHINGTON AVE, EL CAJON, CA, 92020'},
    {typo: 'APT 34-104 SAN YSI, SAN YSIDRO',
    replacement:'APT 34-104, SAN YSIDRO'},
    {typo: 'UNIVERCITY',
    replacement:'UNIVERSITY'},
    {typo: '2095 WEST VISTA WAY VISTA, CA 92083',
    replacement:'1840 WEST DR, VISTA, CA, 92083'},
    {typo: '2095 WEST VISTA WAY VISTA, CA, 92083',
    replacement:'1840 WEST DR, VISTA, CA, 92083'},
    {typo: '5565 GROSSMONT CENTER DR 1 SUITE 211',
    replacement:'5565 GROSSMONT CENTER DRIVE, SUITE 221'},
    {typo: '1620 ALPINE BLVD SUITE 110 ALPINE CA. 91910',
    replacement:'1620 ALPINE BLVD, SUITE 110, ALPINE, CA, 91901'},
    {typo: '3855 HEALTH SCIENCE DR',
    replacement:'3855 HEALTH SCIENCES DR'},
    {typo: '321 E STREET CHULA VISTA CA 91911',
    replacement:'321 E STREET CHULA VISTA CA 91910'},
    {typo: 'NATIONAL CITY CA 919150',
    replacement:'NATIONAL CITY CA 91950'},
    {typo: '408 DICKINSON DR.',
    replacement:'408 DICKINSON ST,'},
    {typo: '751 MEDICAL CENTER CT. 751 MEDICAL CENTER CT., CA 91911 ',
    replacement:'751 MEDICAL CENTER COURT, CHULA VISTA, CA, 91911'},
    {typo: '751 MEDICAL CENTER CT. , CA, 91911',
    replacement:'751 MEDICAL CENTER COURT, CHULA VISTA, CA, 91911'},
    {typo: '211CHULA',
    replacement:'211, CHULA'},
    {typo: '570 S. MOLLISON ST, #1, , C',
    replacement:'570 SOUTH MOLLISON ST, #1C'},
    {typo: '1845 E 12TH ST, NATIONAL CITY , CA 92021',
    replacement:'1845 E 12TH ST, NATIONAL CITY, CA, 91950'},
    {typo: '3364 BEYER BLVD #102 SAN DIEGO',
    replacement:'3364 BEYER BLVD #102 SAN YSIDRO'},
    {typo: 'BEYER BLVD SD 92173',
    replacement:'BEYER BLVD, SAN DIEGO, 92173'},
    {typo: 'STEET',
    replacement:'STREET'},
    {typo: '4150 REGENTS PARK ROW, STE 195 LA JOLLA, CA, 92 320',
    replacement:'4150 REGENTS PARK ROW, STE 195, LA JOLLA, CA, 92037'},
    {typo: '303 Hst',
    replacement:'303 H ST'},
    {typo: '830 BROADWAY APT 40 ELCAJON, CA 92021',
    replacement:'830 BROADWAY, UNIT 40,EL CAJON, CA, 92021'},
    {typo: '704 E GRAND ESCONDIDO 92025',
    replacement:'704 E GRAND AVE, ESCONDIDO, CA, 92025'},
    {typo: 'VITSA',
    replacement:'VISTA'},
    {typo: 'GENESSE',
    replacement:'GENESEE'},
    {typo: '1535 E PLAZA BLVD APT 211 NATIONAL, CA 91950',
    replacement:'1535 E PLAZA BLVD, APT 211, NATIONAL CITY, CA, 91950'},
    {typo: 'GENESEEE',
    replacement:'GENESEE'},
    {typo: '303 HST',
    replacement:'303 H ST'},
    {typo: 'APT 211 NATIONAL, CA',
    replacement:'APT 211 NATIONAL CITY, CA'},
    {typo: '704 E GRAND ESCONDIDO',
    replacement:'704 E GRAND AVE, ESCONDIDO'},
    {typo: 'CAMOUS P',
    replacement:'CAMPUS P'},
    {typo: '5565 GROSSMONT CENTER DRIVE 3',
    replacement:'5565 GROSSMONT CENTER DR'},
    {typo: '4303 VILLAGE DR',
    replacement:'4303 LA JOLLA VILLAGE DR'},
    {typo: 'CHULA VITA',
    replacement:'CHULA VISTA'},
    {typo: '754 MEDICAL CT COURT',
    replacement:'754 MEDICAL CENTER CT'},
    {typo: 'SUITE 106 SD, CA',
    replacement:'SUITE 106, SAN DIEGO, CA'},
    {typo: 'PADUA HLS',
    replacement:'PADUA HILLS'},
    {typo: 'CENTER DRIVE SD CA',
    replacement:'CENTER DRIVE, SAN DIEGO, CA'},
    {typo: '950 EUCLID',
    replacement:'950 S EUCLID'},
    {typo: ' SY CA',
    replacement:' SAN YSIDRO, CA'},
    {typo: 'CHUVISTA',
    replacement:'CHULA VISTA'},
    {typo: '2999 HEALTH CTR DRIVE SD',
    replacement:'2999 HEALTH CTR DRIVE SAN DIEGO'},
    {typo: 'SOSTICE',
    replacement:'SOLSTICE'},
    {typo: 'SANTE FE DR',
    replacement:'SANTA FE DR'},
    {typo: '200 ARBOR DRIVE',
    replacement:'200 WEST ARBOR DR'},
    {typo: '1111 BROADWAY #305',
    replacement:'1111 BROADWAY AV #305'},
    {typo: '1111 BROADWAY 305',
    replacement:'1111 BROADWAY AV #305'},
    {typo: '1111 BROADWAY SUITE 305',
    replacement:'1111 BROADWAY AV #305'},
    {typo: 'CHUL VISTA',
    replacement:'CHULA VISTA'},
    {typo: 'COVINA STREET MIRA MESA',
    replacement:'COVINA STREET, MESA'},
    {typo: '754 MEDICAL CENTER DRIVE',
    replacement:'754 MEDICAL CENTER CT'},
    {typo: '4510 EXECUTIVE DRIVE, SAN DIEGO, CA, 92921',
    replacement:'4510 EXECUTIVE DRIVE, SAN DIEGO, CA, 92121'},
    {typo: '9000 WAKARUSA DR',
    replacement:'9000 WAKARUSA ST'},
    {typo: 'SUITE 360 SD',
    replacement:'SUITE 360, SAN DIEGO'},
    {typo: '9400 CAMPUS DRIVE',
    replacement:'9400 CAMPUS POINT DRIVE'},
    {typo: '345 FST',
    replacement:'345 F ST'},
    {typo: '880 3RD AVE CV 91911',
    replacement:'880 3RD AVE, CHULA VISTA, CA, 91911'},
    {typo: '655 EUCLID',
    replacement:'655 S EUCLID'},
    {typo: '2216 EL CAMINO REAL',
    replacement:'2216 S EL CAMINO REAL'},
    {typo: 'SUITE 610 SD',
    replacement:'SUITE 610, SAN DIEGO'},
    {typo: 'SUITE 4 SD',
    replacement:'SUITE 4, SAN DIEGO'},
    {typo: '46060 EL CAJON B',
    replacement:'4660 EL CAJON B'},
    {typo: 'SUITE 212 SD',
    replacement:'SUITE 212, SAN DIEGO'},
    {typo: '202 S.D.',
    replacement:'202, SAN DIEGO'},
    {typo: '9434 MEDICAL CENTER DRIVE LA JOLLA, CA 92307',
    replacement:'9434 MEDICAL CENTER DRIVE LA JOLLA, CA 92037'},
    {typo: '303CHULA',
    replacement:'303 CHULA'},
    {typo: '880 3RD AV CV 91911',
    replacement:'880 3RD AV, CHULA VISTA, CA, 91911'},
    {typo: 'CA 9203-',
    replacement:'CA 92121'},
    {typo: 'JOLLA VILLAGE SAN',
    replacement:'JOLLA VILLAGE DR SAN'},
    {typo: '3960 HEALTH SCIENCE ',
    replacement:'3960 HEALTH SCIENCES '},
    {typo: 'CLAREMONT',
    replacement:'CLAIREMONT'},
    {typo: '408 DICKINSON 2ND ST',
    replacement:'408 DICKINSON ST'},
    {typo: '408 DICKINSON  2ND ST',
    replacement:'408 DICKINSON ST'},
    {typo: 'SAN DIE,',
    replacement:'SAN DIEGO,'},
    {typo: ' 427 TRANSPORTATION AV',
    replacement:'2427 TRANSPORTATION AV'},
    {typo: 'LOWER LEVER',
    replacement:' '},
    {typo: 'LOWER LEVEL',
    replacement:' '},
    {typo: 'LOWER LEVEL',
    replacement:' '},
    {typo: 'SUITE 201 SD',
    replacement:'SUITE 201, SAN DIEGO'},
    {typo: 'PLAZA VILLAGE 950 L AVE',
    replacement:' 950 L AVE'},
    {typo: '3998 VISTA WAY SUITE 108 OCEANSIDE, CA. PH',
    replacement:'3998 VISTA WAY, SUITE 108, OCEANSIDE, CA, 92056 '},
    {typo: '400 E.',
    replacement:'400 E'},
    {typo: 'VIEW RD. SD',
    replacement:'VIEW RD, SAN DIEGO'},
    {typo: '477 NORTH EL CAMINO REAL A SUITE 102 92024',
    replacement:'477 N EL CAMINO REAL,SUITE 102, ENCINITAS, CA, 92024'},
    {typo: 'N.TORRY',
    replacement:'N TORREY'},
    {typo: '3RD.',
    replacement:'3RD'},
    {typo: 'NORDHAL',
    replacement:'NORDAHL'},
    {typo: 'PARK LANE, SY',
    replacement:'PARK LANE, SAN YSIDRO'},
    {typo: '440 E.',
    replacement:'440 E'},
    {typo: '3RD FLOOR SD',
    replacement:' SAN DIEGO'},
    {typo: 'CA, 9191PER',
    replacement:'CA, 91911'},
    {typo: 'HIGHWAY,94',
    replacement:'HIGHWAY 94'},
    {typo: '754 MEDICAL CENTER, STE. 101',
    replacement:'754 MEDICAL CENTER CT, STE. 101'},
    {typo: 'SA  YSIDRO',
    replacement:'SAN YSIDRO'},
    {typo: 'MAGNOLIA AVE SUITE B, CA 92020',
    replacement:'MAGNOLIA AVE, SUITE B, EL CAJON, CA, 92020'},
    {typo: 'HEALT ',
    replacement:'HEALTH '},
    {typo: '340 8TH',
    replacement:'340 E 8TH'},
    {typo: '754 MEDICAL CENTER SUITE',
    replacement:'754 MEDICAL CENTER CT, SUITE'},
    {typo: '200 ARBOR DR',
    replacement:'200 WEST ARBOR DR'},
    {typo: '855 RD AV',
    replacement:'855 3RD AV'},
    {typo: 'CROOCH',
    replacement:'CROUCH'},
    {typo: 'EL CAJON CA EL CAJON, CA',
    replacement:'EL CAJON, CA'},
    {typo: 'FLOOR SD',
    replacement:'FLOOR, SAN DIEGO'},
    {typo: '9202U1',
    replacement:'92020'},
    {typo: '9400 POINT',
    replacement:'9400 CAMPUS POINT'},
    {typo: 'CENTER DR. CV',
    replacement:'CENTER DR, CHULA VISTA'},
    {typo: '330 BROADWAY',
    replacement:'330 W BROADWAY'},
    {typo: 'VISAT',
    replacement:'VISTA'},
    {typo: 'BROADWAY ROOM 112',
    replacement:'BROADWAY #112'},
    {typo: '764 MEDICAL CENTER DR.',
    replacement:'764 MEDICAL CENTER CT,'},
    {typo: '2067 VISTA WAY',
    replacement:'2067 W VISTA WAY'},
    {typo: 'CA 91EVAL',
    replacement:'CA 91911 EVAL'},
    {typo: 'SUITE 312 SD',
    replacement:'SUITE 312, SAN DIEGO'},
    {typo: '2400 EAST FOURTH',
    replacement:'2400 E 4TH'},
    {typo: '91950-2',
    replacement:'91950'},
    {typo: 'STE121-122',
    replacement:'STE 122'},
    {typo: 'DRIVE SUITE 2 C',
    replacement:'DRIVE SUITE 2C'},
    {typo: '1380 EL CAJON STE',
    replacement:'1380 EL CAJON BLVD, STE'},
    {typo: 'POWEY',
    replacement:'POWAY'},
    {typo: 'EAST 12TH NA',
    replacement:'EAST 12TH ST, NA'},
    {typo: '9350 CAMPUS DR',
    replacement:'9350 CAMPUS POINT DR'},
    {typo: ' 91914-3',
    replacement:' 91914'},
    {typo: '1ST FLOOR,',
    replacement:' '},
    {typo: 'SUITE #2',
    replacement:'SUITE 2'},
    {typo: 'PARKWAY VALLEY',
    replacement:'VALLEY PARKWAY'},
    {typo: 'APT#7',
    replacement:'APT 7'},
    {typo: '4910 DIRECTOR PL',
    replacement:'4910 DIRECTORS PL'},
    {typo: 'BOR DRIVE SD CA',
    replacement:'BOR DRIVE, SAN DIEGO, CA'},
    {typo: '1820 MARRON DR',
    replacement:'1820 MARRON RD'},
    

    
    

    
    

   

   
    
    
    
    
    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
    
    
    
    
    
    
    
    
    

    
    
    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
    

    


    

    
    
        
]